### Create New Account



POST http://localhost:8080/cars/ HTTP/1.1 
content-type: application/json

{
    "id" : 12, 
    "make" : "zwr", 
    "model" : "a11", 
    "mfg" : "2020-01-01",
    "cost" : 789
}

### Getting all cars


GET http://localhost:8080/cars/ 

### Getting single car by id

GET http://localhost:8080/cars/17
